version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-graphql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: graphql_sample
      MYSQL_USER: graphql_user
      MYSQL_PASSWORD: graphql_password
  app:
    container_name: node-graphql
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [db]
    links:
      - db
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
      DB_USER: graphql_user
      DB_PASSWORD: graphql_password
      DB_NAME: graphql_sample
    command: ["/bin/sh", "-c", "./scripts/wait-for db:3306 -- sleep 10;yarn db-migrate;yarn start"]
